name: Build Flutter APK

on:
  workflow_dispatch:  # agar bisa klik "Run workflow" manual di GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'  # Ganti jika kamu pakai versi Flutter lain

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ky-mobile-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
